---
title: "30 days chart challenge - day 15"
description: "positive/negative"
author: "Marcel Ferreira"
date: "2023-04-15"
categories: [R, Dataviz]
image: ""
---

```{r}
library(tidyverse)
library(brasileirao)
library(rvest)
```

## Data


```{r}
url <- "https://en.wikipedia.org/wiki/2019_Campeonato_Brasileiro_S%C3%A9rie_A"




url %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="mw-content-text"]/div[1]/table[7]') %>% 
  html_table(fill = TRUE)


final_table <- list()
tindex <- c(2,2,3,4,4,5,5,
            6,6,6,9,9,8,7,7,7,7)

for(i in 1:17){
  j <- 2005 + i
  url <- glue::glue("https://en.wikipedia.org/wiki/{j}_Campeonato_Brasileiro_S%C3%A9rie_A")
  p1 <- tindex[i]
  
  
  final_table[[i]] <- url %>% 
    read_html() %>% 
    html_node(xpath = glue::glue('//*[@id="mw-content-text"]/div[1]/table[{p1}]')) %>% 
    html_table(fill = TRUE)
  
  print(j)
}
```
```{r}
tab <- final_table %>%
  map(.f = \(x) x %>% mutate(Team = str_replace(Team, "\\(C\\)",""))) %>%
  map(.f = \(x) x %>% mutate(Team = fix_names(Team))) %>%
  map(.f = \(x) x %>% select(Pos,Team)) %>%
  reduce(.f = bind_rows)
```

